language: node_js
node_js:
  - 'lts/*'
  - 10
  - 12
  - node
script: npm run build
before_install: make prep-ci
after_success:
  - npm install coveralls
  - npm run cov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
